export { default as compose } from 'lodash/flowRight'
export { default as flow } from 'lodash/flow'
export { default as isNumber } from 'lodash/isNumber'
export { default as isObject } from 'lodash/isObject'
export { default as isObjectLike } from 'lodash/isObjectLike'
export { default as isString } from 'lodash/isString'
export { default as isUndefined } from 'lodash/isUndefined'

export { utilDefaults as defaults } from './util-defaults'
export { utilDefaultsDeep as defaultsDeep } from './util-defaults-deep'
export { utilDefaultsDeepByKeys as defaultsDeepByKeys } from './util-defaults-deep-by-keys'
export { utilMapValues as mapValues } from './util-map-values'
export { utilOmitBy as omitBy } from './util-omit-by'
export { utilPickBy as pickBy } from './util-pick-by'
export { utilSet as set } from './util-set'
