import type { FunctionComponent } from 'react'

const AppHead: FunctionComponent = () => {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}

export default AppHead
