# https://www.netlifycms.org/docs/configuration-options/

media_folder: 'packages/boilerplate-nextjs/contents/doc/media'
public_folder: 'packages/boilerplate-nextjs/public'

# https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: cms-netlify
  repo: 'DEBT: to add repo'

# https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend:
  url: http://localhost:8081/api/v1

# https://www.netlifycms.org/docs/collection-types/
# https://www.netlifycms.org/docs/widgets/
collections:
  - name: 'doc'
    label: 'Docs'
    folder: 'docs'
    create: true
    slug: '{{category}}-{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Category'
        name: 'category'
        options: ['cicd', 'concept', 'framework', 'tools']
        widget: 'select'

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
