export const PlatformConstant = {
  authenticationClient: 'PlatformAuthenticationClient',
  authenticationClientVariant: { client: 'client' },
  authenticationController: 'PlatformAuthenticationController',
  authenticationModule: 'PlatformAuthenticationModule',
  authenticationService: 'PlatformAuthenticationService',
  authenticationStream: 'PlatformAuthenticationStream',
  dataModule: 'PlatformDataModule',
  dataService: 'PlatformDataService',
  errorModule: 'PlatformErrorModule',
  errorStream: 'PlatformErrorStream',
  eventModule: 'PlatformEventModule',
  eventService: 'PlatformEventService',
  eventStream: 'PlatformEventStream',
  localeModule: 'PlatformLocaleModule',
  localeService: 'PlatformLocaleService',
  queryClient: 'PlatformQueryClient',
  queryClientVariant: { queryClientV5: 'queryClientV5' },
  queryController: 'PlatformQueryController',
  queryModule: 'PlatformQueryModule',
  scriptModule: 'PlatformScriptModule',
  scriptService: 'PlatformScriptService',
} as const
