export const PlatformDependency = {
  authenticationClient: 'Platform_AuthenticationClient',
  authenticationClientVariant: { client: 'client' },
  authenticationController: 'Platform_AuthenticationController',
  authenticationModule: 'Platform_AuthenticationModule',
  authenticationService: 'Platform_AuthenticationService',
  authenticationStream: 'Platform_AuthenticationStream',
  dataModule: 'Platform_DataModule',
  dataService: 'Platform_DataService',
  errorModel: 'Platform_ErrorModel',
  errorModule: 'Platform_ErrorModule',
  errorStream: 'Platform_ErrorStream',
  eventModule: 'Platform_EventModule',
  eventService: 'Platform_EventService',
  eventStream: 'Platform_EventStream',
  filterModel: 'Platform_FilterModel',
  filterModule: 'Platform_FilterModule',
  i18nClient: 'Platform_I18nClient',
  i18nClientVariant: { i18nClientV23: 'i18nClientV23' },
  i18nController: 'Platform_I18nController',
  i18nModule: 'Platform_I18nModule',
  i18nService: 'Platform_I18nService',
  notificationModel: 'Platform_NotificationModel',
  notificationModule: 'Platform_NotificationModule',
  notificationStream: 'Platform_NotificationStream',
  queryClient: 'Platform_QueryClientQuery',
  queryClientVariant: { queryClientV5: 'queryClientV5' },
  queryController: 'Platform_QueryController',
  queryModule: 'Platform_QueryModule',
  queryService: 'Platform_QueryService',
  scriptModule: 'Platform_ScriptModule',
  scriptService: 'Platform_ScriptService',
} as const
