import type { NextPage } from 'next'
import type { AppProps } from 'next/app'
import type { ReactNode } from 'react'
import { Box, ChakraProvider, VStack } from '@chakra-ui/react'
import { QueryClientProvider } from 'react-query'
import { RecoilRoot } from 'recoil'
import Head from 'next/head'

import SectionFooter from '../views/section-footer'
import SectionHeader from '../views/section-header'
import SystemToastErrors from '../views/system-toast-errors'
import SystemToastNotifications from '../views/system-toast-notifications'
import runSetup from '../setup'

const setup = runSetup()

interface Props extends AppProps {
  Component: NextPage & {
    getLayout?: (page: ReactNode) => ReactNode
  }
}

function getLayoutDefault(page: ReactNode) {
  return (
    <>
      <SectionHeader />
      {page}
      <Box flex="1" sx={{ marginTop: '0 !important' }} />
      <SectionFooter />
    </>
  )
}

function MyApp(props: Props) {
  const { Component } = props
  const getLayout = Component.getLayout || getLayoutDefault

  return (
    <RecoilRoot>
      <QueryClientProvider client={setup.queryClient}>
        <ChakraProvider>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <SystemToastErrors />

          <SystemToastNotifications />

          <VStack alignItems="stretch" minHeight="100vh" spacing="10">
            {getLayout(<Component {...props.pageProps} />)}
          </VStack>
        </ChakraProvider>
      </QueryClientProvider>
    </RecoilRoot>
  )
}

export default MyApp
