name: scheduleRegressionTest

# @ 2pm UTC
on:
  schedule:
    - cron: 0 14 * * *

env:
  ARTIFACT_PATH_TEST_MEDIA: artifact-test-media
  NODE_VERSION: 16.4.0
  SITE_DOMAIN: gnowth-boilerplate-test.surge.sh
  SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

jobs:
  e2e_regression:
    container:
      image: cypress/included:7.7.0
      options: --user 1001
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache npm cache on linux
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-setup-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-setup-

      - name: Installing node modules
        run: npm run ci:setup

      - name: Build projects
        run: npm run workspaces:build:dev

      - name: Deploy to test
        run: npm run ci:deploy

      - name: End to end regression tests
        run: npm run ci:test:e2e:regression

      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-test-media
          path: ${{ env.ARTIFACT_PATH_TEST_MEDIA }}
          retention-days: 1

      - name: Clean up test environment
        run: npm run ci:deploy:cleanup
